### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by Avaq** [webistor/webistor-app#48]
For about a week now I've been getting the following error when trying to log in on new.webistor.net:

`UnknownSyncError [Exception... "<no message>" nsresult: "0x805e0006 (<unknown>)" location: "JS frame :: http://new.webistor.net/javascripts/vendor.js?20141013 :: .send :: line 3" data: no] (0): Unknown error`

**Comment by Beanow** [comment]
The workaround for now is to go to `https://new.webistor.net` as opposed to `http://new.webistor.net`. A redirect will be implemented soon to prevent this error.

**Comment by bartwr** [comment]
The redirect is implemented and all should work fine now. Clear your browser cache to make sure you can login. https://webistor.net

**Comment by Avaq** [comment]
:+1:
